nelmio_cors:
    paths:
        '^/api':
            origin_regex: true
            allow_origin: ['*']  
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600